### PR TITLE
added meta tag for keywords

### PR DESCRIPTION
**Pull request by shivaylamba**

### CODE REVIEW

**Comment by shivaylamba** [comment]
I have signed the Google Developers CLA on May 04, 2019 14:58 PDT.

**Comment by shivaylamba** [comment]
Now what to do?

**Comment by KeithMoyer** [comment]
@shivaylamba,

Thanks for the PR! :-)

On a technical front, it looks like there's a missing space before "content=", and the other meta elements do not include the optional forward slash before the end of the void element and this new one should match those.

Could you also share what motivated this change? It's my understanding that the keyword metadata tag is largely without effect nowadays.

**Comment by shivaylamba** [comment]
Hello @KeithMoyer I have edited the changes that you suggested. 
And regarding the meta-tag for keywords, Yes I agree that the keyword metatag's relevancy has dwindled in recent time. But it still provides good option for off page SEO. That's why I tried to include the keywords which are relevant with the asylo website. 
But I do totally agree that the effect has fallen down. But it can still be included. And I really thankyou for your reply on this PR.

**Comment by KeithMoyer** [comment]
Thanks, @shivaylamba.

I agree it, at the very least, is unlikely to cause any harm. I was mostly curious if you saw a specific case where this lacking was causing harm and prompted you to add it.

Two more small changes and I'll be comfortable merging this PR:
- I believe that the canonical form is "keywords" (lowercase), and that would match the other meta tags.
- Could you move it from being clustered with the Open Graph meta tags and up with the standard meta tags (just below the description meta tag)?

**Comment by shivaylamba** [comment]
I have implemented the changes suggested by you. @KeithMoyer  
Thanks again!

**Comment by KeithMoyer** [comment]
Merged. Thanks again!

**Comment by shivaylamba** [comment]
Thanks for the initiative.

**Pull request merged**
